### ISSUE TITLE
Axis label is cut off sometimes

### ISSUE THREAD

**Issue by zhongsp** [CVBDL/EagleEye-App#33]
![image](https://cloud.githubusercontent.com/assets/1198615/18580128/4e50b084-7c2c-11e6-8ca2-7379e5d15faa.png)

Add `chartArea` settings to improve the layout.

**Comment by SijingRang** [comment]
We have tooltips, we could discuss whether this is a issue or not.

**Comment by zhongsp** [comment]
Add `chartArea` option
