### ISSUE TITLE
The chartset will not be updated when you modified it by adding charts with the same 

### ISSUE THREAD

**Issue by SijingRang** [CVBDL/EagleEye-App#37]
![image](https://cloud.githubusercontent.com/assets/13606880/18626675/0c624e26-7e89-11e6-88b7-e72a199efb6c.png)

![image](https://cloud.githubusercontent.com/assets/13606880/18626743/61574cc4-7e89-11e6-8132-1716911e9299.png)

**Comment by zhongsp** [comment]
Mongodb issue.

**Comment by zhongsp** [comment]
Fixed in EagleEye-Platform
